<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_model extends CI_Model
{

    public $table = 'users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
	
	// get data by id
    function get_by_where($search,$single = false)
    {
        $this->db->where($search);
		if($single)
	        return $this->db->get($this->table)->first_row();
		else
			return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL, $location = NULL, $active = NULL) {
		
		if($q!=NULL)
		{			
			$this->db->or_like('username', $q);			
			$this->db->or_like('fname', $q);
			$this->db->or_like('lname', $q);
			$this->db->or_like('phone', $q);
			$this->db->or_like('email', $q);			
		}
		
		if($location>0)
				$this->db->where('location', $location);
		
		if($active==1)
			$this->db->where('active', $active);
		else if($active==2)
		{
			$this->db->where('active', 2);
			$this->db->or_where('active',NULL);	
		}
		
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }
	
	function admin_avail()
	{
		$this->db->where('roles', 1);
        return $this->db->get($this->table)->row();
	}

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $location = NULL, $active = NULL) {
        $this->db->order_by($this->id, $this->order);        
		
		if($q!=NULL)
		{			
			$this->db->or_like('username', $q);			
			$this->db->or_like('fname', $q);
			$this->db->or_like('lname', $q);
			$this->db->or_like('phone', $q);
			$this->db->or_like('email', $q);		
		}
		
		if($location>0)
				$this->db->where('location', $location);
		
		if($active==1)
			$this->db->where('active', $active);
		else if($active==2)
		{
			$this->db->where('active', 2);
			$this->db->or_where('active',NULL);	
		}
				
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-15 14:30:29 */
/* http://harviacode.com */